config/routes.rb
FirehoseHbs::Application.routes.draw do
  get "map/map"

    root 'static_pages#index'
    resources :pics

  

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	#field should map to schema 
	#ImageUploader from the uploaders file 
	mount_uploader :image, ImageUploader
	acts_as_mappable

	# validate that the user added text in form
	validates :image, :presence => true
	validates :place, :presence => true
	validates :description, :presence => true
	validates :location, :presence => true

##end

#added
	#before you save this, do the geocode stuff
	before_save :geocode


#def geocode
	# #set loc to the user input address
	#loc = Geokit::Geocoders::GoogleGeocoder3.geocode(
		#self.address
		#)

	#set lat lng values 
	#self.lat = loc.lat
	#self.lng = loc.lng

	def geocode
	# set loc to the user input address
	loc = Geokit::Geocoders::GoogleGeocoder3.geocode(
		self.location
		)

	#set lat lng values 
	self.lat = loc.lat
	self.lng = loc.lng
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/map_controller.rb
class MapController < ApplicationController
	def map
		#get the value and store it into the database
		#addes filter
		if params[:place].present?
			@pics = Pic.where(:place => params[:place])
		else
			@pics = Pic.all
		end
	end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index 
		#get the value and store it into the database
		#addes filter
		if params[:place].present?
			@pics = Pic.where(:place => params[:place])
		else
			@pics = Pic.all
		end
	end 

	def show
	#get the value and store it into the datab
		@picsAll = Pic.all
		if params[:id].present?
			@pic = Pic.find_by_id(params[:id])
			# show all places nearby 
			@picsNearby = Pic.within(1, origin: @pic)
		end
	end

	def new
		#building a blank item, filling it out on the form
		@pic = Pic.new
	end

	#do...end, def...end, passes all parameters from the simple form into this array
	def create 
		@pic = Pic.create( pic_params )
		#add validation 
		if @pic.persisted?
			redirect_to pics_path
		else
			render :new, :status => :unprocessable_entity
		end
	end

	#function 
	private
	#slurp up these paramaters
	def pic_params
		# permit the user to upload these things into your site 
		params.require(:pic).permit(:place, :description, :location, :image)
	end

	#added for maps
	def map
		#loads most recent place, always pull the last row in the table
		@location = Location.last
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- add this to the top of every page -->
<html>
  <head>
    <title>Hidden NYC</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <!--make a rule to change the background for each page-->
  <body class="<%= "#{params[:controller]}-#{params[:action]}" %>">
  <!--bootstrap responsive nav-->
  <div class="fixednav">
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!--  add link to Ruby code -->
          <%= link_to 'Hidden NYC', root_path, :class => 'brand' %>
     
          <!-- Everything you want hidden at 940px or less, place within here -->
          <div class="nav-collapse collapse">
            <!-- .nav, .navbar-search, .navbar-form, etc // added from basic nav bootstrap  change path for map to #Pic.find(9)-->
            <ul class="nav">
            	<li>
            		<%= link_to 'Shhh...NYC', pics_path %>
            	</li>
            	<!-- add back when you want people to contribute 
              <li>
            		<%= link_to 'Contribute', new_pic_path %>
            	</li> -->
                <li>
                <%= link_to 'Map', map_map_path%>
              </li>
        	 </ul>
          </div> <!-- nav-collapse collapse -->
        </div> <!-- container -->
      </div> <!-- navbar-inner -->
    </div> <!-- navbar navbar-inverse -->
  </div> <!-- fixednav -->

<!-- Google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-46637759-1', 'hiddennyc.herokuapp.com');
  ga('send', 'pageview');
</script>

  <!--pulls in each pages info-->
  <%= yield %>
  </body>
</html>

app/views/map/map.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<title>NYC Adventure Map</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">

<script type='text/javascript'>
// refresh page
(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();
</script>

<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyCPLbu8YjZRwomPf5PC6rIEwAuv57GfR5E&sensor=false"
type="text/javascript"></script>

<script type="text/javascript">

function initialize() {
  var map = new google.maps.Map(
    document.getElementById('map_canvas'), {
      center: new google.maps.LatLng(40.7687, -73.9364),
      zoom: 12,
      mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  $("section").each(function() {
      //take the lat, lng, place from the rails below, split it into an array using the | 
      var encoded_lat_lng = $(this).html();
      var array_version = encoded_lat_lng.split("|");
      var lat = array_version[0];
      var lng = array_version[1];
      var place = array_version[2];
      //var point = new GLatLng(lat, lng);
      var marker = new google.maps.Marker({
            position: new google.maps.LatLng(lat, lng),
            map: map,
            title: place
      });
  }); // Note the additional }); here to close the each loop above
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<!-- split screen left/right, keep map fixed while locations scroll -->
<div id="left">
  <div style="height:100%; width:100%;">
  <!--Map style on Webpage-->
    <div id="map_canvas">
    </div>
  </div>
</div>

<div class="right-contain">
  <div id="right">
    <div>
      <% @pics.each do |pic| %>
      <div class="span4 boxy text-center">
        <h2>
          <%= pic.place %>
        </h2>
        <%= image_tag pic.image %>
        <%= pic.location %>
        <section style= "display:none">
          <%= pic.lat.to_s + "|" + pic.lng.to_s + "|" + pic.place %>
        </section>
      </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<h1 class="h1-custom" style="margin-top: 0px; margin-bottom: 5px; line-height: ">
	New York! 
</h1>
<br/>
<h1 class="h1-custom" style="margin-top: 0px; font-size: 50px; padding: 0px; margin-bottom: 70px;">
	Select a location to find adventures nearby 
</h1>
<div> 
	<!--go through all items in database-->
	<% @pics.each do |pic| %>
	<div class="span4 boxy text-center">
		<h2>
			<%= pic.place %>
		</h2>
		<!-- display the image-->
		<%= image_tag pic.image %>
		<br/>
		<br/>
		<!-- display the image description-->
		<%= pic.description %>
		<br/>
		<br/>
		<!--<%= pic.location %>-->
		<%= link_to pic.location, pic%>
		<br/>
	</div> <!-- boxy -->
	<% end %> 
</div>

app/views/pics/new.html.erb
<div class="span6 offset3 text-center boxycenter" style="margin-top: 50px;">
	<h1 class="h1-custom">
		More NYC...
	</h1>
	<br/>
	<!-- form found on https://github.com/plataformatec/simple_form -->
	<%= simple_form_for @pic do |f|%>
		<%= f.input :place, :label => 'Where should we go?', :placeholder => 'Hayden Planetarium Star Show' %>
		<%= f.input :description, :label => 'Tell me something about it' , :placeholder => 'Stargaze from Manhattan, anytime.'  %>
		<%= f.input :location, :label => 'Address'  , :placeholder => '81 Central Park West, New York, NY 10023' %>
		<br/>
		<br/>
		<%= f.input :image, :label => '...Upload!' %>
	<br/>
	<%=submit_tag 'Save', :class => 'btn btn-info btn-large' %>
	<%end%>
</div>

app/views/pics/show.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<title>NYC Adventure Map</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">

<script type='text/javascript'>
// Refresh page
(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();
</script>

<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyCPLbu8YjZRwomPf5PC6rIEwAuv57GfR5E&sensor=false"
type="text/javascript"></script>
<script type="text/javascript">
    function initialize() {
      var map = new google.maps.Map(
        document.getElementById('map_canvas'), {
          center: new google.maps.LatLng(40.7687, -73.9364),
          zoom: 12,
          mapTypeId: google.maps.MapTypeId.ROADMAP
      });

      $("section").each(function() {
          //take the lat and lng from the rails below, split it into an array using the | 
          var encoded_lat_lng = $(this).html();
          var array_version = encoded_lat_lng.split("|");
          var lat = array_version[0];
          var lng = array_version[1];
          var place = array_version[2];
          var marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat, lng),
                map: map,
                title: place
        });
      }); 

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<!--<div onload="initialize()" onunload="GUnload()">-->
<div id="left">
  <div style="height:100%; width:100%;">

    <!--Map style on Webpage-->
    <div id="map_canvas">
    </div>
  </div>
</div>

<div class="right-contain">
  <div id="right">
    <h1 class="h1-custom" style="margin-top: 0px; line-height: 1.5em; padding-top: 0px">
      Adventures Nearby
    </h1>
    <div id="one" class="hidden">
      <div class="span4 boxy text-center">
        <h2>
          <%= @pic.place %>
        </h2>
        <%= @pic.location %>
        <section style= "display:none">
          <%= @pic.lat.to_s + "|" + @pic.lng.to_s %>
        </section>
      </div>
    </div>

    <div id="nearby" >
      <% @picsNearby.each do |pic| %>
      <div class="span4 boxy text-center">
        <h2>
          <%= pic.place %>
        </h2>
        <%= image_tag pic.image %>
        <%= pic.location %>
        <section style= "display:none">
          <%= pic.lat.to_s + "|" + pic.lng.to_s + "|" + pic.place %>
        </section>
      </div>
      <% end %> 
    </div>
  </div>
</div> <!-- right contain -->

app/views/static_pages/index.html.erb
<!--make a box-->
<div class="span6 offset3 boxy text-center">
	<!--headline 1, most important for SEO-->
	<h1 class="h1-custom">
		Shhh...a view of a hidden NYC
	</h1>
	<br/>
	<h2>
		Enter in secrecy
	</h2> 
	<br/>
	<br/>
	<%= link_to 'Enter a New NYC', pics_path, :class => 'btn btn-primary btn-info' %>
</div>